In [2]:
import  numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([[1.5 , 2 , 3] , [4 , 5 , 6]] , dtype = float)
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [4]:
a

array([1, 2, 3])

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [8]:
arr = np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

In [11]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.ones((7,9))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,10,10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
arr = np.random.randint(20,50,10)
arr

array([24, 37, 35, 37, 24, 23, 28, 33, 38, 27])

# Inspecting Numpy Arrays

In [19]:
a.shape

(3,)

In [20]:
len(b)

2

In [21]:
b.ndim

2

In [22]:
b.size

6

In [23]:
b.dtype

dtype('float64')

In [24]:
b.dtype.name

'float64'

In [25]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Manipulating Numpy Array

In [26]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [27]:
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [30]:
np.delete(b,1,0)

array([[1.5, 2. , 3. ]])

In [31]:
b.reshape(3,2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [32]:
np.append(a,b)

array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ])

# subsetting , slicing , indexing

In [33]:
a

array([1, 2, 3])

In [34]:
a[1]

2

In [35]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [36]:
b[1][1]

5.0

In [37]:
b[1,1]

5.0

In [39]:
a[0:2]

array([1, 2])

In [40]:
b[: , 0:2]

array([[1.5, 2. ],
       [4. , 5. ]])

In [41]:
a[a<2]

array([1])

# Numpy Array Mathematics

# Numpy Arithmetic Operator

In [42]:
a

array([1, 2, 3])

In [43]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [44]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [45]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [46]:
np.subtract(b , a)

array([[0.5, 0. , 0. ],
       [3. , 3. , 3. ]])

In [47]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [48]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
np.sin(b)

array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [50]:
np.log(b)

array([[0.40546511, 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

# Numpy Statistical Operations

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [53]:
a.sum()

6

In [54]:
b.min()

1.5

In [55]:
b.max()

6.0

In [56]:
b.mean()

3.5833333333333335

In [58]:
np.median(b)

3.5

In [59]:
np.std(b)

1.5920810978785667

In [62]:
b.std()

1.5920810978785667